-- -------------------------------------------------
-- PREGUNTA 1

SELECT e.ID, e.AGE, e.NAME, c.INFOACCESSLEVEL, d.OFFICE
FROM EMPLOYEE e, CLERK c, DIRECTOR d
WHERE e.ID = c.ID AND e.ID = d.ID
UNION
SELECT e.ID, e.AGE, e.NAME, NULL, NULL
FROM EMPLOYEE e
WHERE e.id NOT IN (SELECT id FROM CLERK) AND e.id NOT IN (SELECT id FROM DIRECTOR)
UNION
SELECT e.ID, e.AGE, e.NAME, c.INFOACCESSLEVEL, NULL
FROM EMPLOYEE e, CLERK c
WHERE e.ID = c.ID AND e.ID NOT IN (SELECT id FROM DIRECTOR)
UNION
SELECT e.ID, e.AGE, e.NAME, NULL, d.OFFICE
FROM EMPLOYEE e, DIRECTOR d
WHERE e.ID = d.ID AND e.ID NOT IN (SELECT id FROM CLERK)
