-- -------------------------------------------------
-- PREGUNTA 1

CREATE MATERIALIZED VIEW vistaCinc REFRESH COMPLETE ENABLE QUERY REWRITE AS SELECT
	cand,
	pobl,
	MAX(val)
FROM
	CENTMILRESP
GROUP BY
	cand,
	pobl;
	
CREATE MATERIALIZED VIEW vistaU REFRESH COMPLETE ENABLE QUERY REWRITE AS SELECT
	cand,
	MAX(val)
FROM
	CENTMILRESP
GROUP BY
	cand;

-- -------------------------------------------------
-- PREGUNTA 2

CREATE MATERIALIZED VIEW vistaQuatre REFRESH COMPLETE ENABLE QUERY REWRITE AS SELECT
	cand,
	edat,
	AVG(val),
	MAX(val),
	COUNT(*)
FROM
	CENTMILRESP
GROUP BY
	cand,
	edat;

-- -------------------------------------------------
-- PREGUNTA 3

CREATE MATERIALIZED VIEW V3 REFRESH COMPLETE ENABLE QUERY REWRITE AS SELECT
	A,
	SUM(B),
	SUM(C),
	SUM(D),
	COUNT(*)
FROM
	T
GROUP BY
	A;

CREATE MATERIALIZED VIEW V4 REFRESH COMPLETE ENABLE QUERY REWRITE AS SELECT
	A,
	D,
	SUM(B)
FROM
	T
GROUP BY
	A,
	D;

CREATE MATERIALIZED VIEW V2 REFRESH COMPLETE ENABLE QUERY REWRITE AS SELECT
	A,
	C,
	SUM(B)
FROM
	T
GROUP BY
	A,
	C;
